In [2]:
import numpy as np

In [14]:
arr = np.array([[1, 2, 3],[5, 6, 7]])
print(arr)
print(arr.ndim)      #数组维度
print(arr.shape)     #数组形状
print(arr.size)      #数组元素个数
print(arr.dtype)     #数组数据类型
print(arr.T)         #数组的转置

[[1 2 3]
 [5 6 7]]
2
(2, 3)
6
int64
[[1 5]
 [2 6]
 [3 7]]


In [3]:
arr = np.array([1, 2, 3],dtype=np.float64)
print(arr)

[1. 2. 3.]


In [4]:
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [6]:
arr = np.zeros((2,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [8]:
arr = np.zeros((20,),dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [10]:
arr = np.ones((3, 3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
arr = np.empty((3, 3))

In [13]:
arr = np.full((3, 3), 2026)
print(arr)

[[2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]]


In [14]:
arr = np.zeros_like(arr)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.arange(2, 11, 2)  # start, stop, step
print(arr) # 不包括stop

[ 2  4  6  8 10]


In [ ]:
arr = np.linspace(0,100,5,dtype=int) # 取多少个数
print(arr)    # 包括stop
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [22]:
arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [ ]:
arr = np.eye(3,dtype=int) # 单位矩阵
print(arr)
arr = np.diag([5,1,2,3])  # 对角矩阵
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [ ]:
# 随机浮点数(均匀分布)
arr = np.random.rand(2,3)  # 随机数组2*3
print(arr)
arr = np.random.uniform(3,6,(2,3))  #指定范围随机数
print(arr)

[[0.9410422  0.76038282 0.96564692]
 [0.06478715 0.01503969 0.39626902]]
[[5.38102534 4.12738555 4.2821377 ]
 [3.28456437 4.78311734 3.83797425]]


In [ ]:
# 随机整数（均匀分布）
arr = np.random.randint(3, 30,(2,3))
print(arr)

[[13 17 16]
 [22 19 12]]


In [30]:
# 随机数列（正态分布）
arr = np.random.randn(2,3)
print(arr)

[[ 0.63615076 -1.20110089  1.20085285]
 [-0.67365575 -0.88649952  0.14443931]]


In [31]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
